sensors:
  break_beam_1:
    type: break_beam
    pose:
      xyz: [1.6, 2.25, 0.91]
      rpy: [0, 0, 'pi']
  logical_camera_bin1:
    type: logical_camera
    pose:
      xyz: [-0.3, -1.916, 1.7]
      rpy: ['pi/2', 'pi/2', 0]
  logical_camera_bin2:
    type: logical_camera
    pose:
      xyz: [-0.3, -1.15, 1.7]
      rpy: ['pi/2', 'pi/2', 0]
  logical_camera_bin3:
    type: logical_camera
    pose:
      xyz: [-0.3, -0.383, 1.7]
      rpy: ['pi/2', 'pi/2', 0]
  logical_camera_bin4:
    type: logical_camera
    pose:
      xyz: [-0.3, 0.383, 1.7]
      rpy: ['pi/2', 'pi/2', 0]
  logical_camera_bin5:
    type: logical_camera
    pose:
      xyz: [-0.3, 1.15, 1.7]
      rpy: ['pi/2', 'pi/2', 0]
  logical_camera_bin6:
    type: logical_camera
    pose:
      xyz: [-0.3, 1.916, 1.7]
      rpy: ['pi/2', 'pi/2', 0]
  logical_camera_belt1:
    type: logical_camera
    pose:
      xyz: [1.25, 1.15, 1.8]
      rpy: [0, 'pi/2', 0]
  logical_camera_belt2:
    type: logical_camera
    pose:
      xyz: [1.25, -1.15, 1.8]
      rpy: [0, 'pi/2', 0]
 
